export enum SHOP_COLLECTION_TYPES {
   FETCH_PRODUCTS_START = 'shopCollection/FETCH_PRODUCTS_START',
   FETCH_PRODUCTS_SUCCESS = 'shopCollection/FETCH_PRODUCTS_SUCCESS',

   LOAD_MORE_PRODUCTS_START = 'shopCollection/LOAD_MORE_PRODUCTS_START',
   LOAD_MORE_PRODUCTS_SUCCESS = 'shopCollection/LOAD_MORE_PRODUCTS_SUCCESS',
   
   FETCH_PRODUCTS_FAILED = 'shopCollection/FETCH_PRODUCTS_FAILED'
}
